### ISSUE TITLE
Moes ZS-EUB 3 gang switch (TS0013, qewo8dlz) became an EndDevice after OTA from factory image to 1.0.20

### ISSUE THREAD

**Issue by marazmarci** [romasku/tuya-zigbee-switch#124]
I ordered this Zigbee switch: https://www.aliexpress.com/item/1005005178436451.html

When I received it, I paired it to Z2M. Since I already had two of these switches (all of which correctly became a Router after the factory->custom OTA), I already had this in my `configuration.yaml`:

```yaml
ota:
  zigbee_ota_override_index_location: >-
    https://raw.githubusercontent.com/romasku/tuya-zigbee-switch/refs/heads/main/zigbee2mqtt/ota/index_router.json
```

The update appeared on the OTA tab for the new switch, then I started the OTA. Later I noticed that the device is an EndDevice, and not a Router, as I expected. It remains an EndDevice after removing the device from Z2M and re-pairing, and also when pressing a button 10 times, then re-pairing.

It's also interesting that I OTA updated the previous switch from the factory firmware yesterday, and it received the 1.0.19 version, and it correctly became a Router. Then I updated it to 1.0.20, and it stayed being a Router.

**Comment by andrei-lazarov** [comment]
Probably my bad.. I merged the database entries for router and end_device (we had 2 entries per device).  
But I thought I adjusted the scripts correctly. I'll test it and try to come up with a fix.  
Thanks for pointing this out!

Edit: so to clarify: you have the same switch, some units on router and the new one on end_device?

**Comment by marazmarci** [comment]
> Edit: so to clarify: you have the same switch, some units on router and one on end_device?

yes, exactly.

**Comment by marazmarci** [comment]
I performed another OTA, but now using `index_router-FORCE.json`. After it finished, Z2M still showed EndDevice, but then clicked on the ℹ️ interview button, and it got updated on the web UI, and now it shows Router.

I regret not clicking on the interview button before the forced router OTA. Maybe it was a router already? ~~If this is true, it may be beneficial to add a step to the flashing instructions to click on the interview button after updating from the factory firmware.~~ Nevermind, [it is already there](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/updating.md#:~:text=If%20the%20device%20rejoins%3A%20Interview%20and%20Reconfigure%20it.): "_If the device rejoins: Interview and Reconfigure it._". I failed to read the instructions fully, probably because I was too confident after flashing the first one 😂

I guess in this case there were no problem at all, and we can close this issue. Sorry for wasting your time!

**Comment by marazmarci** [comment]
I'll receive another switch soon. I'll be careful to follow the instructions when flashing it, and reopen this issue if it _really_ becomes an EndDevice.

**Comment by andrei-lazarov** [comment]
I figured it might be an interview problem. But I thought removing and re-adding the device does include an interview.. 
Glad it was an easy fix 😂

**Comment by marazmarci** [comment]
I flashed another one, and after following the instructions, it correctly became an EndDevice! All good! 👍
