### ISSUE TITLE
TS0044 4gang (scene remote) switch - custom firmware possible?

### ISSUE THREAD

**Issue by ThePegass** [romasku/tuya-zigbee-switch#171]
Hello,

I have recently bought TS0044:
https://www.zigbee2mqtt.io/devices/TS0044.html
https://www.zigbee2mqtt.io/devices/TS0044_1.html

<img width="895" height="193" alt="Image" src="https://github.com/user-attachments/assets/87677b4c-5eee-4193-b6a2-32e10a9d8d1a" />

Zigbee module used:
 - **Wall switch (TS0044): ZS3L**
  ![Image](https://github.com/user-attachments/assets/250048c7-240a-4f92-bbfe-206da12fda19)
 - **Remote control (TS0044_1): ZT3L**
 ![Image](https://github.com/user-attachments/assets/9e2314e8-17b6-46d2-b833-832b3106eacf)

All of them works fine, however there is short delay between button press and action response in Z2M I would like to eliminate. The delay is most likely because these devices support also doubleclick and it waits 0.5s if second click occurs (double click action detected). This cannot be normally changed. I was looking for alternative custom firmware and found "[tuya-zigbee-switch](https://github.com/romasku/tuya-zigbee-switch)"

Based on readme, module ZT3L is supported, but this TS0044 device is not in the list of supported devices. Would it be possible to create custom firmware for TS0044_1? 

Appreciate any help or guide.
Thanks

**Comment by andrei-lazarov** [comment]
Hi, thanks for your interest in the project! 
Currently the firmware only supports Telink-based chips (address starting with 0xa4c138) like the the ZT3L. 

However Romasku is working on Silicon Labs support (like the ZS3L). Some info is in https://github.com/romasku/tuya-zigbee-switch/issues/14#issuecomment-3357588800. 
I also have the 4-gang scene switch so I will help porting and testing. Will let you know when it will be available (not very soon I imagine).

To port the firmware for the compatible remote, we need to know the pinout of the module: which pins of the ZT3L connect to which peripherals (buttons, LEDs, relays).  
It's best to check with a multimeter, but the traces are visible so we can work it out. I see 5 traces. Snap a picture of the other side of the PCB. Some examples here: https://github.com/romasku/tuya-zigbee-switch/issues/145#issuecomment-3303035527, https://github.com/romasku/tuya-zigbee-switch/issues/146#issuecomment-3302750944

Also that would be the first supported remote. So the firmware needs some changes to allow 'more buttons than relays'. I will try to simulate that let you know when it's safe to upgrade.

**Comment by ThePegass** [comment]
hi. Thanks for your quick response. Yes, 0xa4c138 was the first info I check in Z2M. I would like to achieve immediate response over having more scenes (double-click, long click).  I will trace PCB lines of the remote and will update you with details. BTW, Do these devices (Telink-based chips) share the same firmware? Don't you need the original firmware of the remote?

**Comment by andrei-lazarov** [comment]
> I would like to achieve immediate response over having more scenes (double-click, long click)

I understood. We already implemented 3 **immediate** responses: press, long_press, release. 
I assure you 'press' appears as soon as the button makes contact, no delay.
When we add double and triple clicks, I will take this into consideration and make it optional, so you won't have delays if you don't need multiple-clicks.

---

By the way, do you know about **Zigbee binds**? 

For example, you can bind a Zigbee remote/button to a Zigbee lightbulb for direct control.
The toggle message goes: Button ➡ lightbulb, **so it works even when your server or network is down.** 

With software automations, the messages take a much longer route:
Button ➡ coordinator ➡ server ➡ automation logic ➡ coordinator ➡ lightbulb
This is much less reliable, because the simple action of turning on the lights depends on too many links.

**The custom firmware fully supports binds and is the main reason I'm using it.**

I am curious if your devices support binding on original firmware. **Can you try and let me know?** 
My 4-gang scene switch is actually model [TS004F](https://www.zigbee2mqtt.io/devices/TS004F.html) (but the internals look identical) and it does not support binds as far as I can tell. Some devices that do: [SNZB-01](https://www.zigbee2mqtt.io/devices/SNZB-01.html#sonoff-snzb-01), all IKEA remotes.

---

**Also, the original firmware needs to have the OTA cluster** (even if it does not show up in the OTA tab, just the cluster), otherwise you would need a UART flasher to perform the update by wire.

---

For the pinout, note that the [diagram](https://developer.tuya.com/en/docs/iot/zt3l-module-datasheet?id=Ka438n1j8nuvu#title-5-Pin%20definition) is mirrored (shows the back of the board). 
And we also need to know whether the peripherals are **active low or active high**. So if one side of the button/LED is connected to a GPIO pin, check if the other side is connected to VCC or GND.

---

> BTW, Do these devices (Telink-based chips) share the same firmware? Don't you need the original firmware of the remote?

Here's my simplified understanding of this: 
What we call 'firmware' / build / binary refers to the combination of 'operating system' and 'app' that run on the device. You can not separate these or install them individually. 
So even if the 'os' is identical, the firmware is unique to each device, because it runs a different 'app': different features (remote, switch, socket, sensor) and different pinouts (to match the internal structure of the device).

Edit: Our custom firmware binaries only differ in pinouts. In the future we will have a single / a few unified binaries (with an empty default pinout), because it is very inefficient to build the same firmware 50+ times. The downside is the user has to input the pinout by himself.

We don't need the original firmware because we can't reverse-engineer it, and we don't need to. Telink provides the SDK and IDE (from which the toolchain is extracted) for building firmware, for free. So the 'os' part is mostly handled by their SDK.

However, you can back-up the original firmware with a hardware flasher, in case you want to restore it later. Flashing by wire is the only way to revert to original firmware, and we only have a few binaries backed-up (as it's quite tedious).

---

Please join our Discord server if you're still curious about the project, or need help with the pinout / your network / bindings - so I can get back to you quicker.

**Comment by ThePegass** [comment]
>  We already implemented 3 **immediate** responses: press, long_press, release. I assure you 'press' appears as soon as the button makes contact, no delay. When we add double and triple clicks, I will take this into consideration and make it optional, so you won't have delays if you don't need multiple-clicks.

Exactly. Double/tripple-click makes no sense (can be optional) with "immediate click". Long click can still work. I read you implemented the option to change "hold" time until it triggers "long click". Original firmware is 5s, what is too long IMO. 2-3s is optimal.

> By the way, do you know about **Zigbee binds**?

Im really new in all the "smart home" topic. Installed home assistant week ago. Yes, I know about it,  haven't tied so far. I have only a few zigbee devices (switches, bulb, PIR), so I don think it makes really sense in my case. Anyway, tried to bind 1st button to T2 bulb. Bind button keeps inactive. There is only "genOta" and "genTime" in the output clusters.

<img width="922" height="342" alt="Image" src="https://github.com/user-attachments/assets/63448363-41e2-4040-956c-2890094eec88" />

>
**PCB analysis** (nothing professional, I'm just enthusiastic :)) :
 - bottom side of the PCB is the voltage regulator with filtering caps on in/out
 - four buttons switches ground to 4 inputs of ZT3L:
Button 1 ---> pin 5
Button 2 ---> pin 7
Button 3 ---> pin 6
Button 4 ---> pin 4
 - LED diode is supplied from VCC(via resistor) and GND comes N-channel mosfet. Mosfet (G) is controlled from pin 10.
 - ping (hw reset) is permanently "high" level via resistor

Long press of the button1 activates zigbee pairing mode.

<img width="789" height="1037" alt="Image" src="https://github.com/user-attachments/assets/6441d2ec-db1f-4216-acea-eed23cd0a3cd" />

**Comment by andrei-lazarov** [comment]
> I read you implemented the option to change "hold" time until it triggers "long click".

That's right. You can choose anything between 0-5s. Defaults to 0.8ms.

> Im really new in all the "smart home" topic. Installed home assistant week ago.

**This has to be a record! So deep into the rabbit hole, you have found custom firmware within a week??** 😱 
And you're already out here disassembling your remotes..

> Bind button keeps inactive

Yes, that's unfortunate.. No binds on stock firmware. 
Generally onOff and levelCtrl show up under clusters. Tick them and click bind, then press = toggle, long_press = dim up/down.

> There is only "genOta" and "genTime" in the output clusters.

That's good! It means you'll be able to update to custom fw OTA.

Pinout drawings are also so good, I'll provide them as examples to the next person!
I'll add your device to the database and you can update right away.. 
I said I need to implement remotes (allow more buttons than relays), but we can actually flash '4 buttons + 4 relays' firmware. We just assign the 'relays' to some unused GPIO pins. And remove them later.
I have flashed 4-gang fw on a 3-gang device and the extra peripherals mapped to unused pins didn't cause any issues.

It would still be the first remote and battery-powered device to see Romasku's firmware, so if don't mind it being a 'test mule', I'll provide the build and instructions in a bit

**Comment by andrei-lazarov** [comment]
**I need the 'Zigbee manufacturer' of the remote.** 
It's one of these 3: `_TZ3000_dziaict4`, `_TZ3000_mh9px7cq`, `_TZ3000_j61x9rxn`

Also the link to buy it and the battery type would be nice to have in the DB. 
Here is the entry so far:

```yaml
TUYA_REMOTE_TS0044:
  human_name: Tuya 4-button remote
  neutral: without
  battery: null
  device_type: end_device
  tuya_model_name: TS0044
  tuya_manufacturer_name: null
  stock_converter_manufacturer: Tuya
  stock_converter_model: TS0044
  override_z2m_device: TS0044_1
  zb_module: ZT3L
  family: Telink
  config_str: null    ;TS0044-CUS;LC0i;SD2u;RD4;SC2u;RA0;SC3u;RB4;SD7u;RB5;M;
  alt_config_str: null
  old_manufacturer_names: null
  old_zb_models: null
  tuya_manufacturer_id: 4417
  tuya_image_type: 54179
  firmware_image_type: 43563
  build: yes
  status: In progress
  info: Does not have relays
  github_issue: https://github.com/romasku/tuya-zigbee-switch/issues/171
  store: null
```

**Comment by ThePegass** [comment]
> **This has to be a record! So deep into the rabbit hole, you have found custom firmware within a week??** 😱 And you're already out here disassembling your remotes..

😄 not really. Started searching for custom firmware possibilities just two days ago when I realized it is hard to find zigbee remote which perform immediate click.

**My remote vendor is:** 
_TZ3000_mh9px7cq (Zigbee 4 button remote - 12 scene)
Brand: ATLO
**Specs:**
<img width="590" height="645" alt="Image" src="https://github.com/user-attachments/assets/d579a459-5042-450f-965b-ec9a2ad31d44" />

The picture of the remote looks different in Z2M database. It is because more variants of TS0044_1 exists (differents size, butttons, body shape)
<img width="1005" height="450" alt="Image" src="https://github.com/user-attachments/assets/11185aea-fc97-4614-925d-0e910758d2c9" />

These two remotes should be the same. I have the left one and found the same from MOES brand and also unbranded version.
<img width="963" height="378" alt="Image" src="https://github.com/user-attachments/assets/3536ea05-2223-4fe1-ae79-823af7b88d85" />


Links (1st is where I bought it):
[Allegro.pl - ATLO](https://allegro.pl/oferta/pilot-atlo-rc4-tuya-zigbee-tuya-smart-da-16513965398)
[Aliexpres - Unbranded](https://www.aliexpress.com/item/1005005792534172.html)
[smarthome-europe.com - MOES](https://moeshouse.com/products/zigbee-4-gang-scene-remote?srsltid=AfmBOop3lj4dFqCUocNfFU-S4hg-BHzwrovKDUNmpRynva0BK5fvg3x9)

**Comment by andrei-lazarov** [comment]
Ok. Follow the updating guide, but use my branch: [build/TUYA_REMOTE_TS0044](https://github.com/andrei-lazarov/tuya-zigbee-switch/tree/build/TUYA_REMOTE_TS0044) instead of main.

So these [converters](https://github.com/andrei-lazarov/tuya-zigbee-switch/tree/build/TUYA_REMOTE_TS0044/zigbee2mqtt/converters) and this index:
```
https://raw.githubusercontent.com/andrei-lazarov/tuya-zigbee-switch/refs/heads/build/TUYA_REMOTE_TS0044/zigbee2mqtt/ota/index_end_device.json
```

Let me know how it goes! I will also upload the correct device picture to Z2M

**Comment by ThePegass** [comment]
That was fast! Wow. 
I followed the instruction, but got some errors. What I did:

**1. replace converters** (two js files from your branch):
<img width="943" height="295" alt="Image" src="https://github.com/user-attachments/assets/501cc267-1efb-4f0b-b58e-556d0391b95e" />

**2. restart Z2M**
**3. copy index url** (index_end_device.json) to OTA configuration, checked file "/homeassistant/zigbee2mqtt/configuration.yaml":
<img width="974" height="69" alt="Image" src="https://github.com/user-attachments/assets/6377fef0-e017-44ac-bb42-3f71f5c71949" />
**4. again restart Z2M**

**I got following error when Reconfigure device:**
`[10/13/2025, 5:45:35 PM] z2m: Failed to configure '0xa4c13892f2e73b9e', attempt 1 (Error: ZCL command 0xa4c13892f2e73b9e/1 genBasic.read(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:594:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:20)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:20)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:20)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:20)
    at /app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:492:20
    at Queue.execute (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:490:16)
    at Request.send (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:86:25)
    at Endpoint.sendRequest (/app/node_modules/.pnpm/zigbee-herdsman@6.1.5/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:360:20))`

**and error when "check updates":**
`[10/13/2025, 5:49:08 PM] z2m: Failed to check if update available for '0xa4c13892f2e73b9e' (Device didn't respond to OTA request)`

Did I miss something?

**Comment by andrei-lazarov** [comment]
End_devices (battery-powered stuff) stay asleep most of the time to save energy. You have to physically interact with them to wake them up before you can send Zigbee commands to them.

So press some buttons before you check for updates. If the issue persists, reset and re-pair the device.

That being said, our firmware is not designed for remotes.. I' don't know if it would ever enter sleep in custom firmware, so expect it to drain the battery quicker (maybe remove it when not in use).

**Comment by ThePegass** [comment]
I pressed button to be sure device is not in sleep. Tried remove battery for couple of minutes and pair again. No success. Getting the same error  _Device didn't respond to OTA request)_

Device state:
`{
    "battery": 100,
    "last_seen": "2025-10-13T18:30:45+02:00",
    "linkquality": 76,
    "voltage": 3000,
    "action": "3_single",
    "update": {
        "installed_version": -1,
        "latest_version": -1,
        "state": null
    }
}`

Does it mean it actually does not support OTA updates? Could it has something to do with my zigbee controller?

**Comment by ThePegass** [comment]
some progress. Removed battery, then pressed "check update", insert battery and update appeared. However update goes to error again.

<img width="1269" height="147" alt="Image" src="https://github.com/user-attachments/assets/3a6266db-dd38-44e5-88d6-d6ecf1ac6314" />

<img width="482" height="252" alt="Image" src="https://github.com/user-attachments/assets/91aa5533-23dc-4b37-af88-07647ba0ff67" />

**Comment by ThePegass** [comment]
Done! Firmware was updated. Took a bit long, more than 5 minutes.

<img width="1194" height="453" alt="Image" src="https://github.com/user-attachments/assets/0bb61260-711b-409a-b541-0c1b3fc1c397" />

<img width="298" height="647" alt="Image" src="https://github.com/user-attachments/assets/d18fd46a-ab95-4981-8b00-c2bb0905652e" />

Quick obsevations:
 - LED is permanently on/off based on toggle switch and work opposite way (toggle on = LED off, toggle off = LED permanently on)
 - buttons 1, 2 and 3 changes state of Relay 0, Relay 1, Relay 2. **Button 4 does nothing (no state change of the Relay 3)**
 - after some time LED starts blinking. During this time, no action happens when press buttons. Don't know what does it means, interview request? Tried to interview, failed, then LED stop blinking and Remote works again 
 - as the firmware is originally for relay module, it is a bit overkill for Remote device 😄 . E.g power on behavior makes no sense as there are no physical relays which can be in ON/OFF state.
 - there are lot of binds and some reporting's, do I need it?

- **What perfectly works and make me smiling is the "press_start" relay mode. Created simple automation to toggle on/off one of my light. It is instant!!! And this is exactly what I wanted to achieve.**

I can see room for changes and simplification of the firmware to meet "Remote" needs. Make it more "Remote switch"  firmware than "Relay switch" firmware. Can I someone help or contribute on firmware modifications? Have no clue how much is it complicated.

Current firmware can be used to control lights or other devices with some workarounds. Previous "1_single_click" action of the original firmware needs to be replaced by "Relay_0 is turned on or off"

**Comment by andrei-lazarov** [comment]
**Awesome! 🎉 What helped you fix the error and finally trigger the update?**  
I didn't have anything else to suggest, other than mashing the buttons and going closer to the coordinator (I still see the signal quality is low). What coordinator do you use?  

> LED is permanently on/off based on toggle switch and work opposite way (toggle on = LED off, toggle off = LED permanently on)

We can invert the LED behavior in the device config field:  
`LC0i;` -> this means network indicator LED on pin C0, inverted. **Just remove the `i`.**   
The new config string will apply as soon as you click away from the field.  

> buttons 1, 2 and 3 changes state of Relay 0, Relay 1, Relay 2. Button 4 does nothing (no state change of the Relay 3)

That likely means we got the pin wrong for the fourth button:  
I put `SD7u;` -> 'switch' on pin D7, 10K ohm internal pull-up resistor.  
Maybe it goes under the module, to the other side at B4? I assumed B4 is unused so I used it for the third 'relay': `RB4;`. You can **carefully** experiment with this in the config string. Write it in a text editor and paste it only when it's complete, so you don't brick your device with a wrong config. Also do not assign the same pin twice!

> after some time LED starts blinking. During this time, no action happens when press buttons. Don't know what does it means, interview request? Tried to interview, failed, then LED stop blinking and Remote works again

The LED is assigned as a network indicator.  
It blinks when the device is in pairing mode. Otherwise, it follows the manual state. **Maybe you triggered a reset?**  
We have 2 reset methods: 
1. hold the reset button (you don't have one) 
2. quickly press a switch (button in your case) 10 times in a row.  
The counter resets after 0.8 seconds, so I believe it's difficult to trigger it on accident?  
But this is by far the most debated topic.. I will make the number (10) configurable soon. 

> as the firmware is originally for relay module, it is a bit overkill for Remote device 😄 . E.g power on behavior makes no sense as there are no physical relays which can be in ON/OFF state.

Yes, I will improve the firmware for remotes in the future. **Thanks for being the first to test it!**  
You can open your `switch_custom.js` file and delete/disable stuff. Put `//` in front of the features, under `TS0044_1`.  
But you can't disable the relay controls and power-on-behavior, as these are provided by default.  
I suggest leaving it as it, you will eventually learn the options are still useful on your remote.  
The extra 'relays' are actually necessary for 'toggle_smart_sync'. 

> there are lot of binds and some reporting's, do I need it?

Endpoints 1-4 are the buttons, so you need them.  
Endpoints 5-8 are the 'relays' so you mostly don't need them. But again, I suggest leaving them as is.

> "press_start" relay mode  
> "Relay_0 is turned on or off"

**You are actually using it wrong..**
- Like I said, **use binds if possible**:  
Bind endpoint 1 of the remote to endpoint 1 of the bulb (onOff and levelCtrl)  
press = toggle, hold = dim up/down (alternating)
- If binds are not possible:  
Listen to the 'press action' changing, not for relays toggling. This way it works even in 'detached' mode.  
HomeAssistant -> Automation -> Trigger -> Entity -> State  
Now search the entities for 'press action'.  
~~Press = from 'released' to 'pressed'~~
~~Long press = from 'pressed' to 'long_press'~~
Short press = from `press` to `released`
Long press = from `long_press` to `released`

> Can I someone help or contribute on firmware modifications? 

Of course, you can help if you have any knowledge of C programming.  
The code is available in the repository, there are building instructions in the docs and we can chat on Discord.  
But you need a spare device and a UART flasher for testing. And the learning curve is a little steep.  
So read the docs and get more familiar with the firmware first.

**Comment by ThePegass** [comment]
I think, with the original firmware, device goes to sleep immediately after each button press. I realized this when "check update" worked after re-insert battery and then device went probably to sleep very quicky and firmware update failed. So I tried to start update while pressing any button quicky (keeping device wake on) and that was the point. Update started.

LQI was low because I was in another room (during updating moved device close to coordinator). I use  [ZStack3x0 AVATTO Zigbee Dongle 3.0](https://www.amazon.de/AVATTO-Zigbee2mqtt-CC2652P-Chip-Zigbee-Ger%C3%A4ten-schwarz/dp/B0FB8QKXHZ/ref=asc_df_B0FB8QKXHZ?language=de_DE&mcid=366add36500631deb97a5bf4c6041ef9&tag=detxtgostdde-21&linkCode=df0&hvadid=718119110801&hvpos=&hvnetw=g&hvrand=6827188165458601820&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1000824&hvtargid=pla-2440687613413&gad_source=1&th=1)], based on CC2652P + CP2102N chip. I know SONOFF dongle is more common, but was not available in the eshop. SONOFF Dongle Plus is available now, based on specs it is actually the same as dongle from AVATTO. SONOFF has newer version "E" based on EFR32MG21 + CH9102F. What is your opinion?

**RELAY 4**
As for the relay 4, that was my mistake. Had a look on PCB again and noticed, pin D7 is actually not soldered. Connection continues under the board to B4:
<img width="666" height="854" alt="Image" src="https://github.com/user-attachments/assets/3a5664e0-b9c6-45fb-acff-4e0241a6e46b" />

**LED**
 - Yes please, you can invert the logic.
 - with original firmware, LED was ON as long as button was pressed (short press = short blink). Dont know if you can modify it (not important, just "nice to have")

**RESET**
>quickly press a switch (button in your case) 10 times in a row

Which button, first?

**EVENT binds**
> HomeAssistant -> Automation -> Trigger -> Entity -> State

Thanks. This was exactly I was searching for. But I checked option only in Trigger -> Device. 

**POWER SOURCE**
Device is detected as "Main (Single phase)" power source. Can you set it to "Battery powered"? 
>our firmware is not designed for remotes.. I' don't know if it would ever enter sleep in custom firmware, so expect it to drain the battery quicker (maybe remove it when not in use).

Hmm, maybe changing to "Battery powered" cause the device to go into sleep mode after some time? Maybe not.

I would say the firmware is usable, even not designed for Remote control. 

I have no experiences in C, only VB. UART is on the way.

**Comment by ThePegass** [comment]
I received Sonoff Zigbee Dongle Plus. I was expecting it is "P" version, after opening it I found out that it was "E" version. I was curious so replaced my AVATTO(zstack) coordinator by Sonoff(ember). After some initials issues, Z2M is was and running with new dongle. No issues so far and LQI is much better for all zigbee devices.

First I did not understand what do you mean by "config string". 
Did not find explanation. I assume:
L=Light,
S=Switch, 
R=Relay,
[Ax,Bx,Cx,Dx]=I/O pin
u=?
M=?

SD2u;RD4 means Switch input connected to pin D2 activates output D4 for the relay.

I set it to: 
mh9px7cq;TS0044-CUS;LC0;SD2u;RD4;SC2u;RA0;SC3u;RB4;SB4u;RB5;M;

 - led inverted
 - SD7u > SD4u (4th button works for relay 3)

**Comment by andrei-lazarov** [comment]
> SONOFF has newer version "E" based on EFR32MG21 + CH9102F. What is your opinion?

People on the internet are pretty stubborn and keep recommending the Texas Instruments CC2xxx chips.  
But in our little community we consider the Silicon Labs EFR32 better.. 
It feels more reliable and seems to be the only one capable of handling 120+ devices.  
I'm using the SONOFF dongle E in two places without issues, but I'm only at 12-13 devices 🙂 

> Connection continues under the board to B4

I will update the config string with the correct pin and inverted LED.

> RESET Which button, first?

Any button.

> Trigger -> Device

Using Device is bad because it's harder to re-do the automations if you ever replace the device.  
It's better to use entity states - because when you get a new device, you can give it the old entity name, and all your automations stay the same.

> Can you set it to "Battery powered"?

I will do that, but it's just a piece of text and won't change anything.

> with original firmware, LED was ON as long as button was pressed (short press = short blink). Dont know if you can modify it (not important, just "nice to have")

Will keep in mind!

**Comment by andrei-lazarov** [comment]
> I received Sonoff Zigbee Dongle Plus

That's good. Also update its firmware. Plug into PC and visit [sonoff-dongle-flasher](https://dongle.sonoff.tech/sonoff-dongle-flasher/)

> "config string"

You understood it correctly. It is explained in the porting guide. 
You can read the docs.. I do repeat a lot of information in these threads.
`u` is 10K ohm pull-up resistor. 
`M` defaults your 'switches' to 'momentary' because your remote has momentary buttons.

> `SC3u;RB4;SB4u;RB5;M;`

I said don't assign the same pin twice (B4).. put the relay to the unused D7

**Comment by ThePegass** [comment]
Thanks for all your hints and effort.

> > Can you set it to "Battery powered"?
> 
> I will do that, but it's just a piece of text and won't change anything.
> 
You are right, it is piece of text (my devices are _Battery_, _Main(single phase_) and _DC Source_). Actually it have influence when "Availability check" is activated in the Z2M settings. There are different intervals for Active and Passive device. ZM2 must read this information from the firmware, most likely not based on this plain text, but there must be any param in the firmware which determines if device is Active or Passive.

>I said don't assign the same pin twice (B4).. put the relay to the unused D7

Oh, I guess Im blind 🤦 . Have read the string more times and overlooked B4 anyway. Thanks

**Comment by ThePegass** [comment]
Hello Andy. I found a major problem when your firmware is used in the Remote. It is battery consumption. Original firmware is obviously designed to go into sleep, I measured consumption ~4uA (expected battery life 1-2 years). With your firmware, consumption is ~700uA (expected battery life few days). Since the firmware is designed for relay switch (Main powered) it make sense it does no go into sleep mode. Something prevents sleep mode.


Started reading docs (building...)
Since have verry little experience with github, asked AI for support 😄  I forked your branch and start digging in. If I understand it properly, firmware is built out of /src. At total noob I searched for any _slep_ or _power_ 

**app_cfg.h**
 PM_ENABLE is 0, maybe this prevents device go into sleep?
<img width="283" height="129" alt="Image" src="https://github.com/user-attachments/assets/0f4853c4-57e3-48eb-8bab-162e200477dd" />
There are couple of conditions based on PM_ENABLE in other files.

I found in _basic_cluster.c_:
<img width="390" height="23" alt="Image" src="https://github.com/user-attachments/assets/ac82c1a7-9a5c-4036-bb97-259f5240754e" />
This seems to define power source, shown as _Main (Single phase)_ in Z2M

Have much more questions 😄 , main are:
 - how did you get (read) firmware from the device
 - where all those .c and .h files came from?
 - is there any documentation about the files and params, e.g. what is equivalent of POWER_SOURCE_MAINS_1_PHASE when device is battery powered 
 - how do you modify the firmware (what tools do you use? like VS code or something else?)

PS: I already join your Discord.

Sorry for bothering you, I really like you firmware and want to you use, but power management needs to be fixes. And I would like to help (if possible).

**Comment by andrei-lazarov** [comment]
> PM_ENABLE is 0, maybe this prevents device go into sleep?

Indeed, that sounds like it

> how did you get (read) firmware from the device

You mean the original firmware? You use a hardware flasher to read the entire memory content of the device. But obviously it's overwritten now. You need to buy another unit to get the original firmware.

> where all those .c and .h files came from?

The ones in src/ are written by Romasku. There is some info at the bottom of readme.md for resources. 
The ones in sdk/ are provided by Telink.

> is there any documentation about the files and params, e.g. what is equivalent of POWER_SOURCE_MAINS_1_PHASE when device is battery powered

Yes. If you follow the building steps you will get the sdk/ folder. You will find there all the Zigbee functions and parameters provided by Telink, along with examples.

This should come up if you install the sdk and search the whole project. 

```c
/* Power Source Attribute values */
#define POWER_SOURCE_UNKNOWN                              	0x00
#define POWER_SOURCE_MAINS_1_PHASE                        	0x01
#define POWER_SOURCE_MAINS_3_PHASE                        	0x02
#define POWER_SOURCE_BATTERY                              	0x03
#define POWER_SOURCE_DC                                   	0x04
#define POWER_SOURCE_EMERG_MAINS_CONST_PWR                	0x05
#define POWER_SOURCE_EMERG_MAINS_XFER_SW                  	0x06
```

> how do you modify the firmware (what tools do you use? like VS code or something else?)

I use VS code, but any code editor will work.

> And I would like to help (if possible).

I appreciate your help! 
I don't know how everything works, Romasku wrote the firmware by himself. I joined later to add devices, features and grow the community. But hopefully I can point you in the right direction. 
I don't have any remotes yet, but I should get some to test as well.

By the way, the sister project [doctor64/tuyaZigbee](https://github.com/doctor64/tuyaZigbee) says it supports a remote (wireless switch). I did not check it out yet. Don't know if it would be helpful or overwhelming..

**Comment by ThePegass** [comment]
I tried to change power source to POWER_SOURCE_BATTERY and build fw online, then force OTA. After interviewing the device, Z2M detected device as Battery. Power consumption was little bit lover but still too high. Set PM_ENABLE to 1 (again force OTA) makes device unstable, very slow, unresponsive, LED was crazy flashing (e.g. few second of flashing, then no light, then again flashing and sometimes ON for a few seconds). Updating to your build took about 50minutes (about 24 before).

It looks that much more has to be done in the code to properly set the power management (go to deep sleep, wake on button press, battery voltage detection...). It too complicated for me to understand the Telink code (for now). Saw other guy on discord who will try to have a look.  

I saw doctor64 project already, looks abandoned. Found interesting discussion about low power (https://github.com/doctor64/tuyaZigbee/issues/4)

**Comment by andrei-lazarov** [comment]
Small correction here: 

> Press = from 'released' to 'pressed'
Long press = from 'pressed' to 'long_press'

The previous usage will trigger both press and long_press when you long_press. 
This is the correct way to do it:

Short press = from `press` to `released`
Long press = from `long_press` to `released`

Thanks for sharing your findings! Hopefully we'll fix power management in the near future

**Comment by romasku** [comment]
Hi, the 1.1.0 firmware should reduce the average consumption to around ~150 µA based on my measurements.
It’s still far from proper sleep levels, but at least it’s some improvement.

**Comment by lacrimal** [comment]
Spotted that ZS3L is now supported (i know that battery devices are special case) so want to go back to TS0044 4 gang switch _TZ3000_wkai4ga5 from beginning of the topic. Will it be hepfull if i will map butons ? to ZS3L. Also have spare TS0044, so because it is programmable by wire - i can test some firmware when needed.

**Comment by ThePegass** [comment]
Hi @romasku . Thanks for updating me. Yes 150 µA is still too much for battery powered switch/remote. I ended up with my custom firmware. No double-click, no long-click action, no battery level reporting (this would be helpful, but was not able to code it).
Just simple immediate status change. Changed Exposes from "trigger" (exposing Actions) to "binary switch" (ON/OFF state) using custom converter. Consumption is ~3.6µA.
So actually long click can be achieved by automation in HO ("when status changed to ON for xx seconds).
<img width="1230" height="495" alt="Image" src="https://github.com/user-attachments/assets/0eb2c2dd-1da6-401a-bc2d-c22e873a4fb5" />
<img width="372" height="604" alt="Image" src="https://github.com/user-attachments/assets/9168f0df-3947-4065-b60f-20188b3bbf5b" />

**Comment by andrei-lazarov** [comment]
@lacrimal I have the `_TZ3000_xabckq1v` [TS004F](https://www.zigbee2mqtt.io/devices/TS004F.html#tuya-ts004f).
It looks identical to the pictures in the first message.

I mapped the pinout some time ago: 
- LEDs: C1, C2, C0, D0
other side 0Ω to VCC, so active low
- buttons: A0, A3, A4, B0
other side 1kΩ to VCC, so active high?

You could confirm if it's the same for `_TZ3000_wkai4ga5`.
I'll let you know when there is any progress / a build available for testing.

@ThePegass what's the ID for your square remote?

**Comment by ThePegass** [comment]
My wall (square) remote is  _TZ3000_wkai4ga5

**Comment by lacrimal** [comment]
> [@lacrimal](https://github.com/lacrimal) I have the `_TZ3000_xabckq1v` [TS004F](https://www.zigbee2mqtt.io/devices/TS004F.html#tuya-ts004f). It looks identical to the pictures in the first message.
> 
> I mapped the pinout some time ago:
> 
>     * LEDs: C1, C2, C0, D0
>       other side 0Ω to VCC, so active low
> 
>     * buttons: A0, A3, A4, B0
>       other side 1kΩ to VCC, so active high?

Confirming:

Buttons - active is high:
PA00 -> SW1
PA03 -> SW2
PA04 -> SW3
PB00 -> SW4

Leds - active is low:
ADC_PC01 -> LED1
PC02 -> LED2
PC00 -> LED3
PD00 -> LED4

**Comment by FeepingCreature** [comment]
I have a TS0041 _TZ3000_4upl1fcj battery powered one button zigbee wall switch and am also very interested in a firmware that stripped everything but short press without any artificial delay. Lmk if I can do anything to help or test.

**Comment by andrei-lazarov** [comment]
@FeepingCreature first step would be identifying the chip (Telink or Silabs) and mapping its pinout, like we did above.
Then I'll let you know when a build is available for testing.

**Comment by malocycling** [comment]
As I'm also looking forward to this functionality I could support your activities by testing on a single button device HOBEIAN ZG-101ZL using the TLSR8258 chip.

**Comment by FeepingCreature** [comment]
~~Ah, TS0041 _TZ3000_4upl1fcj is a ZS3L. Will take it to the other thread.~~

moved back!

The _TZ3000_4upl1fcj looks to also be a ZS3L.
That's the MOES ZigBee Smart 1 Gang, cell battery-powered. https://www.amazon.de/-/en/Wireless-without-Conductor-Capacitor-Required/dp/B096W232HT?th=1 

Anything I can do to test? I have a usb-to-uart but I don't actually know anything about electronics. I can probably flash something if you tell me where to stick the wires.

(Note: I'm not *100%* sure it's the 4upl1fcj, I bought it a week after one that's definitely a 4upl and it's the same product and looks the same. But I didn't connect it before opening it up.)

![](https://i.imgur.com/YT1Kxcx.png)

**Comment by andrei-lazarov** [comment]
Thank you @FeepingCreature for the picture. 
For now you should just connect it and find the ID.
We don't have a build for battery-powered devices yet.

The board looks identical to our 4-gangs (first message in thread), so I can actually map the pinout to all variants (1,2,3,4 gangs).
But you can still trace it with a multi-meter to confirm, if you're curious: [diagrams/ZS3L_front.png](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/diagrams/ZS3L_front.png)

Also the USB-to-UART is likely not compatible with the Silabs chip. You need a J-link: [flashing/silabs.md](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/flashing/silabs.md)

**Comment by FeepingCreature** [comment]
Thanks! Got it connected and it's definitely a TS0041 _TZ3000_4upl1fcj, as expected. I don't actually have a multimeter, so I'll be grabbing a usb ft232h board and waiting warmly. :)

**Comment by luisfavila** [comment]
I've just read all this as I also have a bunch of _TZ3000_uaa99arv TS0044 4 gang ones from MOES that I'd like to try the custom firmware on. Is there no sleep mode in the firmware yet, so it would drain their battery?

**Comment by andrei-lazarov** [comment]
Progress here: 
- https://github.com/romasku/tuya-zigbee-switch/pull/342

**Comment by Hydron-4hv** [comment]
Great to see this progress - I've got a couple of Moes scene switches that I'd like to try this on once I get a programmer. I see 5uA drain listed in supported devices page - sounds pretty acceptable as a starting point, the original FW on my 3-gang one runs about 3.6uA.
See below pics of the insides (and I really mean that!) of https://www.zigbee2mqtt.io/devices/ZT-SR-EU4.html and the 3-gang version:

![Image](https://github.com/user-attachments/assets/6749fede-e278-49c9-bc04-0add41aa80a3)
![Image](https://github.com/user-attachments/assets/30bba3ed-cf50-42a5-b0b2-0921697770b8)
![Image](https://github.com/user-attachments/assets/ae71f70d-58ee-41c9-84b7-61b060611c42)

**Comment by lacrimal** [comment]
So actual status is that work done by @RealByron (thanks for huge effort) is partially implemented by @romasku (also thanks for your work) in #377. Battery optimizations are ready for 'field tests' whenever TS0044 is Telink based, however Silabs will not benefit from that changes and is still waiting for implementation ?

**Comment by andrei-lazarov** [comment]
I see we have Silabs merged as well
- https://github.com/romasku/tuya-zigbee-switch/pull/381

I need to go through all [remotes](https://github.com/romasku/tuya-zigbee-switch/issues?q=state%3Aopen%20label%3A%22remote%22) posted by you guys and add everything to the database.
Will also test it myself, I'm very excited 🙂

**Comment by andrei-lazarov** [comment]
@Hydron-4hv did you X-Ray the board?? 😱 So cool

**Comment by lacrimal** [comment]
> I see we have Silabs merged as well
> 
>     * [Silabs ADC support #381](https://github.com/romasku/tuya-zigbee-switch/pull/381)
> 
> 
> I need to go through all [remotes](https://github.com/romasku/tuya-zigbee-switch/issues?q=state%3Aopen%20label%3A%22remote%22) posted by you guys and add everything to the database. Will also test it myself, I'm very excited 🙂

Oh yes - did not saw #381, so I'm getting my jlink and will give a try :-)

**Comment by Hydron-4hv** [comment]
@andrei-lazarov seeing as you're adding stuff to the DB already, I've added the issue above with the pinouts of the switches I showed pics/xrays of above (issue also needs to be tagged as "remote"). Let me know if you'd rather I add them and make a PR.

Hopefully I can use a Raspberry Pi + OpenOCD to flash so I don't need to wait on an Aliexpress Jlink

**Comment by lacrimal** [comment]
Found it difficult to work with OpenOCD, needed to guess size of binary dump, it was polluted with garbage. Also several times lost settings. So hunted for Jlink on Ali and now have v7 for ~6USD. It work more predictable.

**Comment by Hydron-4hv** [comment]
OK thanks for the heads up - will place an AliE order for a JLink (should have done it a few days ago), I have a few things to get me to choice or bundle threshold anyway. Any particular reason to go with v7 (vs v9)?

**Comment by lacrimal** [comment]
> OK thanks for the heads up - will place an AliE order for a JLink (should have done it a few days ago), I have a few things to get me to choice or bundle threshold anyway. Any particular reason to go with v7 (vs v9)?

Sorry was wrong, mine is clone of v9 (V9-G), is most popular one, there is no point to buy better one (consider better only if you are going to be professional with newest devices). Most China clones also have wrongly described pins so I needed to use pin 19 described as 5V supply because in reality it suplies with 3.3V, meanwhile pin 2 described as 3.3V is NC. Best idea is to measure it before use. Everything else did by manual from [here](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/flashing/silabs.md)

Anyways, by now not see any working binary from `rs/silabs-battery-devices` to be compatible with `_TZ3000_wkai4ga5`

**Comment by Ctrl-F4** [comment]
> Anyways, by now not see any working binary from `rs/silabs-battery-devices` to be compatible with `_TZ3000_wkai4ga5`

zigbeeModel: ['TS0044']
model: 'TS0044'
vendor: '_TZ3000_wkai4ga5'
"manufacturerCode":4098
"imageType":5634
MOES ESW-0ZAA-EU

Same device here, flashed with [REMOTE_TUYA_TS004F_END_DEVICE](https://github.com/romasku/tuya-zigbee-switch/tree/main/bin/end_device/REMOTE_TUYA_TS004F_END_DEVICE) and seems to work well.

Original FW dump:

[orig_fw_TZ3000_wkai4ga5.zip](https://github.com/user-attachments/files/26384487/orig_fw_TZ3000_wkai4ga5.zip)

**Comment by lacrimal** [comment]
> > Anyways, by now not see any working binary from `rs/silabs-battery-devices` to be compatible with `_TZ3000_wkai4ga5`
> 
> zigbeeModel: ['TS0044'] model: 'TS0044' vendor: '_TZ3000_wkai4ga5' "manufacturerCode":4098 "imageType":5634 MOES ESW-0ZAA-EU
> 
> Same device here, flashed with [REMOTE_TUYA_TS004F_END_DEVICE](https://github.com/romasku/tuya-zigbee-switch/tree/main/bin/end_device/REMOTE_TUYA_TS004F_END_DEVICE) and seems to work well.
> 
> Original FW dump:
> 
> [orig_fw_TZ3000_wkai4ga5.zip](https://github.com/user-attachments/files/26384487/orig_fw_TZ3000_wkai4ga5.zip)

Nope, it is dead with this from main branch [REMOTE_TUYA_TS004F_END_DEVICE](https://github.com/romasku/tuya-zigbee-switch/tree/main/bin/end_device/REMOTE_TUYA_TS004F_END_DEVICE), I'm doing it by Simplicity commander, first flashing generic bootloader and second flashing above .s37 file.

Your dump is working fine with my device even parameters in user dump are same as mine original dump. So guessing - there is some difference in flashing procedure or in device itself. Can you give exact steps how your flashing procedure looks like ?

**Comment by Ctrl-F4** [comment]
@lacrimal 

Hmm same steps taken, not sure. 

<img width="600" height="181" alt="Image" src="https://github.com/user-attachments/assets/be440af5-61c4-4f5b-b295-a2e9c8a0cd1a" />

My device seems to work with config `SA0d;IC1i;SA3d;IC2i;SA4d;IC0i;SB0d;ID0i;BTA0;M;`
I can try to revert to stock fw and try the steps again (maybe this weekend)

Btw how to extract those parameters in user dumps? I noticed the [extract_pinout_from_silabs_data.py](https://github.com/romasku/tuya-zigbee-switch/blob/main/helper_scripts/extract_pinout_from_silabs_data.py) but have not found out yet  the correct syntax.

Edit: @lacrimal  glad you figured it out, thanks for clarify how to use the pinout scripts.

**Comment by lacrimal** [comment]
Figured out - it is working now - my bad was overriding boot loader with firmware using bin file instead s37. So boot loader data was overwritten.

Measured sleep state power draw and it is indeed about 5,1uA, binding works flawlessly with my 2ch relay. 

`Btw how to extract those parameters in user dumps? I noticed the [extract_pinout_from_silabs_data.py](https://github.com/romasku/tuya-zigbee-switch/blob/main/helper_scripts/extract_pinout_from_silabs_data.py) but have not found out yet the correct syntax.`

Did not extracted them, my mapping was manual but quick test shows that output:

```
#>python extract_pinout_from_silabs_data.py userdata_dump_TS0044.bin
{'bt1_pin': '1', 'led1_pin': '11', 'rsthold': '10', 'net_trig': '0', 'led_md_slt': '2', 'jv': '1.0.0', 'led2_lv': '0', 'led4_lv': '0', 'max_V': '3000', 'battery_type': '0', 'min_V': '2500', 'led4_pin': '16', 'bt3_lv': '1', 'bt1_lv': '1', 'bt4_pin': '8', 'module': 'ZS3L', 'bt3_pin': '5', 'led3_pin': '10', 'net_t': '45', 'samp_type': '0', 'led1_lv': '0', 'bt4_lv': '1', 'bt2_pin': '4', 'led3_lv': '0', 'ch_num': '4', 'led2_pin': '12', 'bt2_lv': '1', 'crc': '84'}
SA0u;IC1;SA3u;IC2;SA4u;IC0;SB0u;ID0;
```
This script is parser and translator, you need *.bin dump of your userdata, it will extract internal processor pinout and translate it to pin map. It is important to differ internal pinout saved in userspace vs external pinout - it differs.

**Comment by hllhll** [comment]
Hi all
People in this discussion above reports some ota successes.how can i flash it ota? Looks like device does respond (using various sleep tricks). but no fw available. Only need to build it somehiw and put it somewhere ?

Looks like the batt drainage issue as appear on the devices page is now resolved with tge latest merge ,right ?

**Comment by lacrimal** [comment]
If you are flashing slilabs chips only way is to use flash by wire, I believe OTA option is only for telink devices.

An you are right main branch have now battery drain about 5uA, if you are using TS0044 you can flash TS004F , be aware to make backup of your user space and program space as s37  or hex files before flashing.


Someone told me this when I was in asked same question:
"There is a misunderstanding regarding how OTA works for stock Tuya devices.
Initial Flash: You CANNOT flash custom firmware (like PTVO or your own build) over-the-air to a stock device. The original Tuya bootloader will only accept digitally signed updates from Tuya's servers.
Wired First: To use custom firmware, you must perform the first flash via a physical connection (using J-Link or USB-TTL converter) to overwrite the original bootloader/firmware.
OTA later: Only after you have flashed a custom firmware (which has the OTA cluster enabled and doesn't check for Tuya signatures), you will be able to perform future updates via Zigbee2MQTT's OTA panel.
In short: Since your device is stock, you have to open it and solder wires for the first flash. There is no 'software-only' way to convert it."

**Comment by Hydron-4hv** [comment]
Got my J-Link yesterday, reflashed both Moes scene switches (can contribute factory firmware I pulled off them if required). I have them both now working in Z2M, with some quirks however:
- Instructions don't make it clear which .s37 file to flash (I picked the TS004F file, as it was mentioned above and is the only remote file for silabs)
- The first switch (4-gang) had some difficulty adding the config string. It may have been poor PSU connection though (battery is not very stable when the board is outside the case). Once I did get it set and re-interviewed/configured, it showed up as a TS004F and used the TS004F converter, which works correctly. I was expecting TS0044-MA as per the config string, I will remove and rejoin to test this again. **_Edit - removing and re-adding (had to pull the battery to re-pair) fixed the reported model_**
- The second switch (3-gang) was much easier to pair (I was powering with clip leads at this point), but once I replaced the config string it came up as unsupported - there is no TS0043-MA converter in the Z2M external converter file in this repo. I managed to get it working by adding my own converter (copied and modified the TS004F one), but shouldn't the device-db entry automatically generate the converter during build? (I did copy the latest converter from the main branch to Z2M before trying).

Finally, I did see about 5uA current draw in idle conditions - this is perfectly acceptable for long battery life, and not far off the stock firmware :). Now all I'm missing is multi-click support, which I believe is being worked on? (original FW has double click support, which is handy).

**Comment by andrei-lazarov** [comment]
Sorry for the delay! I went through the threads now and added the remotes.

Also started the build action, so you should find binaries/OTAs for each model when it's finished.

Need to improve the workflow, database is difficult to manage and build is inefficient..

**Comment by Hydron-4hv** [comment]
Just realised that the build action hadn't been triggered when I flashed mine (I pulled the config string from the commit directly), which explains why the converter wasn't there! I've replaced my custom converter conf with the newly built one and it's now working :).

Thanks for all the work on this, I now have the 4-gang happily bound to another Moes relay running this FW, along with some IKEA lights, with a couple of other lights controlled via automations (one is a tuya dimmer that may be a future target though).

**Comment by lacrimal** [comment]
Have some 'behavior report' for my 4gang _TZ3000_wkai4ga5 using 1.1.2-af9cc999 firmware with direct binding support:

1. When the entire power grid goes down and no routers are available, the device immediately starts flashing all four LEDs every second. It remains in this state indefinitely.
2. Once power is restored, the device fails to reconnect automatically. It stays in the flashing state.
3. The device does not respond to the standard 10-click reset sequence in above state, if any button other than button 4 is used. Pressing buttons 1, 2, or 3 10x causes the device to freeze completely.
4. Restoration of functionality currently requires a full battery pull followed by enabling "Permit Join" in the coordinator software.
5. Binding is lost and need to be restored (that is probably expected but should it be permanent?)

**Comment by lacrimal** [comment]
Guys, do you have any idea why device is not rejoin after short period of network unavailability ?
This is about 5 minutes, if it is about 2 minutes it will back however need to enable joining.
It's not look like power safe mode,  _TZ3000_wkai4ga5 can blink to death.
Also - like said before 10x push-to-reset is not working in this state.
To be honest - removing every device from wall mount to remove battery and map binding is little annoying :-)
